# GitHub Sponsors (optional - uncomment and add your username)
# github: [Nicktronix]

# Patreon (optional)
# patreon: your_patreon_username

# Ko-fi (optional)
# ko_fi: your_kofi_username

# Buy Me a Coffee (optional)
# custom: ["https://www.buymeacoffee.com/your_username"]
